const items=[
['movie','电影 · 反复回看','爱在黎明破晓前','VIENNA · 1995','一场走不完的夜谈。最喜欢两个陌生人把普通街道走成宇宙的样子。','https://wsrv.nl/?url=https%3A%2F%2Fmedia.themoviedb.org%2Ft%2Fp%2Fw440_and_h660_face%2Fkf1Jb1c2JAOqjuzA3H4oDM263uB.jpg'],['movie','电影 · 治愈动画','哈尔的移动城堡','MAGIC · 2004','想在有风的草原散步，也想拥有一扇通往不同城市的任意门。','https://wsrv.nl/?url=https%3A%2F%2Fmedia.themoviedb.org%2Ft%2Fp%2Fw440_and_h660_face%2F13kOl2v0nD2OLbVSHnHk8GUFEhO.jpg'],['movie','电影 · 光影收藏','重庆森林','HONG KONG · 1994','罐头会过期，关系也会；但某些镜头的绿色永远新鲜。','https://wsrv.nl/?url=https%3A%2F%2Fmedia.themoviedb.org%2Ft%2Fp%2Fw440_and_h660_face%2F43I9DcNoCzpyzK8JCkJYpHqHqGG.jpg'],['game','游戏 · 冒险地图','塞尔达传说：旷野之息','HYRULE · 2017','第一次从初始台地滑翔下去时，真的觉得世界无限大。','https://wsrv.nl/?url=https%3A%2F%2Fassets.nintendo.com%2Fimage%2Fupload%2Ff_auto%2Cq_auto%2Cw_960%2Fncom%2Fen_US%2Fgames%2Fswitch%2Ft%2Fthe-legend-of-zelda-breath-of-the-wild-switch%2Fhero'],['game','游戏 · 慢慢生活','星露谷物语','PELICAN TOWN · 2016','种下一颗防风草，等一个晴天。像素小镇也有四季和好朋友。','https://cdn.akamai.steamstatic.com/steam/apps/413150/header.jpg'],['game','游戏 · 一人旅途','风之旅人','SILENT DESERT · 2012','没有语言也可以相遇。那段一起飞过沙丘的路，至今很轻。','https://cdn.akamai.steamstatic.com/steam/apps/638230/header.jpg'],['travel','旅行 · 秋日小记','京都的散步日','KYOTO · 2024.11','在哲学之道捡了一片红叶，傍晚吃到热腾腾的汤豆腐。','https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=80'],['travel','旅行 · 海风来信','里斯本的黄色电车','LISBON · 2023.06','上坡时电车叮当作响。蓝色瓷砖、晾衣绳和一整片明亮的海。','https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=900&q=80'],['travel','旅行 · 山野呼吸','大理的云与风','DALI · 2025.04','租了一辆小自行车绕洱海。风把烦恼吹得比云还远。','https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=80']].map((x,i)=>({type:x[0],label:x[1],title:x[2],meta:x[3],note:x[4],img:x[5],id:i}));
items.splice(7,2,
  {type:'travel',label:'旅行 · 街巷漫游',title:'大阪的街头午后',meta:'OSAKA · 2025.03',note:'白天穿过道顿堀的街巷，招牌和人潮都很有精神。',img:'https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=900&q=80'},
  {type:'travel',label:'旅行 · 海港散步',title:'神户港的海风',meta:'KOBE · 2025.03',note:'海湾边的摩天轮慢慢转着，港口的风吹得人很清醒。',img:'https://images.unsplash.com/photo-1726176391835-fec272fed32f?q=80&w=1740&auto=format&fit=crop'},
  {type:'travel',label:'旅行 · 城市夜景',title:'上海的外滩夜色',meta:'SHANGHAI · 2025.05',note:'东方明珠立在灯火之间，黄浦江把两岸的光揉成一片。',img:'https://images.unsplash.com/photo-1529458026081-439a0f7715b6?q=80&w=1742&auto=format&fit=crop'},
  {type:'travel',label:'旅行 · 湖畔慢游',title:'杭州的西湖',meta:'HANGZHOU · 2025.04',note:'湖面很静，小船慢慢划过去，时间也跟着慢下来。',img:'https://images.unsplash.com/photo-1747798678108-ba9a8606d58b?fm=jpg&q=60&w=3000&auto=format&fit=crop'},
  {type:'travel',label:'旅行 · 园林小记',title:'苏州的园林窗景',meta:'SUZHOU · 2025.04',note:'从花窗望出去，池水、绿意和亭子正好被框成一幅画。',img:'https://images.unsplash.com/photo-1705990777259-90aec7105e4e?fm=jpg&q=60&w=3000&auto=format&fit=crop'},
  {type:'travel',label:'旅行 · 梧桐树影',title:'南京的梧桐路',meta:'NANJING · 2025.06',note:'沿着成荫的街道慢慢走，树影把夏天分成一格一格。',img:'https://images.unsplash.com/photo-1635176061729-35ca541a03a1?fm=jpg&q=60&w=3000&auto=format&fit=crop'},
  {type:'travel',label:'旅行 · 海边日记',title:'青岛的礁石海岸',meta:'QINGDAO · 2025.06',note:'在礁石边坐一会儿，海风和浪声把步子都放慢了。',img:'https://images.unsplash.com/photo-1682425895495-92603d898979?fm=jpg&q=60&w=3000&auto=format&fit=crop'},
  {type:'travel',label:'旅行 · 江城夜色',title:'武汉的江边晚风',meta:'WUHAN · 2025.07',note:'江面把一整排霓虹灯收进倒影，夜风正好吹过来。',img:'https://images.unsplash.com/photo-1663301365306-a76cfe6a1ae0?fm=jpg&q=60&w=3000&auto=format&fit=crop'}
);
items.push(
  {type:'movie',label:'电影 · 怦然心动',title:'千与千寻',meta:'SPIRITED AWAY · 2001',note:'穿过隧道以后，名字和勇气都要自己慢慢找回来。',img:'https://wsrv.nl/?url=https%3A%2F%2Fmedia.themoviedb.org%2Ft%2Fp%2Fw440_and_h660_face%2F39wmItIWsg5sZMyRUHLkWBcuVCM.jpg'},
  {type:'movie',label:'电影 · 甜点与冒险',title:'布达佩斯大饭店',meta:'ZUBROWKA · 2014',note:'粉色外墙、紫罗兰甜点，还有一场精致又荒诞的逃亡。',img:'https://wsrv.nl/?url=https%3A%2F%2Fmedia.themoviedb.org%2Ft%2Fp%2Fw440_and_h660_face%2FeWdyYQreja6JGCzqHWXpWHDrrPo.jpg'},
  {type:'movie',label:'电影 · 夏日心事',title:'花样年华',meta:'HONG KONG · 2000',note:'走廊、旗袍与克制的心事，像一首没有说完的歌。',img:'https://wsrv.nl/?url=https%3A%2F%2Fmedia.themoviedb.org%2Ft%2Fp%2Fw440_and_h660_face%2FiYypPT4bhqXfq1b6EnmxvRt6b2Y.jpg'},
  {type:'game',label:'游戏 · 神话冒险',title:'哈迪斯',meta:'UNDERWORLD · 2020',note:'一次次从冥界出发，每次失败都像和老朋友再聊一会儿。',img:'https://cdn.akamai.steamstatic.com/steam/apps/1145360/header.jpg'},
  {type:'game',label:'游戏 · 探索地图',title:'空洞骑士',meta:'HALLOWNEST · 2017',note:'在安静得只剩回声的地下王国，寻找每一盏微小的灯。',img:'https://cdn.akamai.steamstatic.com/steam/apps/367520/header.jpg'},
  {type:'game',label:'游戏 · 双人冒险',title:'双人成行',meta:'BOOK OF LOVE · 2021',note:'最好的关卡，是两个人一起想办法越过去的那一段。',img:'https://cdn.akamai.steamstatic.com/steam/apps/1426210/header.jpg'}
);
items.forEach((item,index)=>item.id=index);
let mode='all',saved=new Set(JSON.parse(localStorage.getItem('archive-favorites')||'[]'));const grid=document.querySelector('#cards'),empty=document.querySelector('#empty'),search=document.querySelector('#search'),dialog=document.querySelector('dialog');
function draw(){const q=search.value.trim();const view=items.filter(x=>(mode==='all'||mode==='favorite'&&saved.has(x.id)||x.type===mode)&&(`${x.title}${x.note}${x.label}`).includes(q));grid.innerHTML=view.map(x=>`<article class="card"><div class="photo"><img src="${x.img}" alt="${x.title}"><button class="heart ${saved.has(x.id)?'saved':''}" data-heart="${x.id}" aria-label="收藏">${saved.has(x.id)?'♥':'♡'}</button><span class="tag">${x.type==='movie'?'电影':x.type==='game'?'游戏':'旅行'}</span></div><div class="body"><p class="meta">${x.meta}</p><h2>${x.title}</h2><p>${x.note}</p><button class="open" data-open="${x.id}">翻开这页 →</button></div></article>`).join('');empty.hidden=!!view.length;document.querySelectorAll('[data-heart]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=+b.dataset.heart;saved.has(id)?saved.delete(id):saved.add(id);localStorage.setItem('archive-favorites',JSON.stringify([...saved]));draw()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openItem(+b.dataset.open))}function openItem(id){const x=items[id];document.querySelector('#detail').innerHTML=`<img src="${x.img}" alt="${x.title}"><p class="meta">${x.label} · ${x.meta}</p><h2>${x.title}</h2><p>${x.note}</p><p>这一页记录的不是攻略或评分，而是当时那个被触动的自己。</p>`;dialog.showModal()}document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{mode=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));draw()});search.oninput=draw;document.querySelector('.close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};draw();
